// ---------------------------------------------------------------------------
// The outbox, the publisher, and the consumer.
//
// What these tests are for: the pipeline's correctness claims are all about SQL and ordering, and
// both are checkable without a broker. The SQL is rendered by real drizzle over a fake socket
// (tests/helpers/fake-pg.js); the producer is a recorder. What is NOT covered here is Kafka's own
// behaviour — partition assignment, rebalances, idempotent-producer semantics — which is what
// scripts/events/outbox-drill.mjs exercises against a real broker.
// ---------------------------------------------------------------------------
import { jest } from '@jest/globals';
import { fakeDb, allSql } from './helpers/fake-pg.js';

/** A producer that records what it was asked to send. */
function fakeProducer({ failWith = null } = {}) {
  const sent = [];
  return {
    sent,
    async send(payload) {
      if (failWith) throw failWith;
      sent.push(payload);
      return [{ topicName: payload.topic, partition: 0, baseOffset: '0' }];
    },
  };
}

const outboxRow = (over = {}) => ({
  id: 1,
  aggregate_type: 'deal',
  aggregate_id: '100',
  event_type: 'deal.created',
  event_id: 'ev-0001',
  payload: { id: 100, owner_id: 7, title: 'Acquire Initech' },
  created_at: new Date('2026-09-05T10:00:00.000Z'),
  published_at: null,
  attempts: 0,
  available_at: new Date('2026-09-05T10:00:00.000Z'),
  last_error: null,
  dead_lettered_at: null,
  ...over,
});

/** Load a module with the database mocked out. */
async function withDb(results, specifier) {
  jest.resetModules();
  const fake = fakeDb({ results });
  jest.unstable_mockModule('#config/database.js', () => ({
    db: fake.db,
    pool: null,
    closeDatabase: async () => ({ closed: false }),
    pingDatabase: async () => ({ ok: true }),
    poolStats: () => null,
    prewarmPool: async () => ({ warmed: 0 }),
  }));
  const mod = await import(specifier);
  return { mod, ...fake };
}

describe('the claim query', () => {
  it('skips locked rows, filters on the partial-index predicate, and orders oldest first', async () => {
    const { mod, db, queries } = await withDb([[outboxRow()]], '#events/outbox.service.js');
    await mod.claimBatch(db, { limit: 50 });

    const sql = queries[0].text.toLowerCase();
    // SKIP LOCKED is what makes this a work queue: a second publisher passes over rows the first
    // holds instead of blocking behind them.
    expect(sql).toContain('for update skip locked');
    // Matches `outbox_unpublished_idx` — the partial index over exactly the backlog.
    expect(sql).toContain('"published_at" is null');
    expect(sql).toContain('"dead_lettered_at" is null');
    expect(sql).toContain('"available_at" <= now()');
    // Total order. Publishing row 2 before row 1 for the same aggregate is precisely what the
    // partition key exists to prevent, so the read side must not introduce it.
    expect(sql).toMatch(/order by .*"available_at".*"id"/);
    expect(queries[0].params).toContain(50);
  });
});

describe('enqueue', () => {
  it('writes the event with a generated id and a stringified aggregate id', async () => {
    const { mod, db, queries } = await withDb(
      [[{ id: 9, event_id: 'x' }]],
      '#events/outbox.service.js'
    );

    await mod.enqueueEvent(db, {
      aggregateType: 'deal',
      aggregateId: 100,
      eventType: 'deal.created',
      payload: { id: 100 },
    });

    const params = queries[0].params;
    expect(params).toContain('deal');
    // A string, because the column is varchar: aggregates in other tables may not have numeric ids
    // and a single partition-key format keeps the publisher from having to know.
    expect(params).toContain('100');
    // A UUID generated by the WRITER — stable across every redelivery, which is what makes consumer
    // deduplication possible at all.
    expect(params.some((p) => /^[0-9a-f-]{36}$/.test(String(p)))).toBe(true);
  });
});

describe('marking outcomes', () => {
  it('records a publish with the database clock', async () => {
    const { mod, db, queries } = await withDb(
      [[{ id: 1 }, { id: 2 }]],
      '#events/outbox.service.js'
    );
    const count = await mod.markPublished(db, [1, 2]);

    expect(count).toBe(2);
    // `now()`, not a client timestamp: the publisher and the database may disagree, and the row's
    // own transaction is the authority on when it happened.
    expect(queries[0].text.toLowerCase()).toContain('"published_at" = now()');
  });

  it('backs off exponentially by pushing available_at into the future', async () => {
    const { mod, db, queries } = await withDb([[]], '#events/outbox.service.js');
    const result = await mod.markFailed(db, outboxRow({ attempts: 2 }), new Error('broker down'));

    expect(result.attempts).toBe(3);
    expect(result.exhausted).toBe(false);
    // Backoff as a column value rather than a sleep: the poller's WHERE clause cannot see the row
    // until it is due, so the delay survives a publisher restart.
    expect(queries[0].text.toLowerCase()).toContain('now() + $');
    expect(queries[0].params.some((p) => String(p).includes('milliseconds'))).toBe(true);
  });

  it('dead-letters after the attempt ceiling, without deleting the row', async () => {
    const { mod, db, queries } = await withDb([[]], '#events/outbox.service.js');
    const result = await mod.markFailed(
      db,
      outboxRow({ attempts: mod.OUTBOX_MAX_ATTEMPTS - 1 }),
      new Error('still down')
    );

    expect(result.exhausted).toBe(true);
    // Marked, not removed: a dead-letter queue you cannot query from the database is one nobody
    // reads.
    expect(queries[0].text.toLowerCase()).toContain('"dead_lettered_at" = now()');
    expect(allSql(queries)).not.toContain('delete from');
  });
});

describe('the publisher', () => {
  it('sends nothing when the outbox is empty', async () => {
    const { mod, queries } = await withDb([undefined, [], undefined], '#events/publisher.js');
    const producer = fakeProducer();

    const result = await mod.publishOnce({ producer });

    expect(result).toEqual({ claimed: 0, published: 0, failed: 0 });
    expect(producer.sent).toHaveLength(0);
    // The transaction is still opened and closed — the claim has to be inside one — but nothing
    // else happens. This is the shape of 99% of poll cycles.
    expect(allSql(queries)).toMatch(/begin[\s\S]*commit/);
  });

  it('keys every message by aggregate, so one deal stays in one partition', async () => {
    const rows = [
      outboxRow({ id: 1, aggregate_id: '100' }),
      outboxRow({ id: 2, aggregate_id: '200' }),
    ];
    const { mod } = await withDb(
      [undefined, rows, [{ id: 1 }, { id: 2 }], undefined],
      '#events/publisher.js'
    );
    const producer = fakeProducer();

    const result = await mod.publishOnce({ producer });

    expect(result).toEqual({ claimed: 2, published: 2, failed: 0 });
    const messages = producer.sent[0].messages;
    // Kafka guarantees order within a partition and nothing across partitions. A null key would
    // spread these round-robin and let a consumer see a stage change before the deal exists.
    expect(messages.map((m) => m.key)).toEqual(['deal:100', 'deal:200']);
  });

  it('publishes a versioned envelope with routable headers', async () => {
    const { mod } = await withDb(
      [undefined, [outboxRow()], [{ id: 1 }], undefined],
      '#events/publisher.js'
    );
    const producer = fakeProducer();

    await mod.publishOnce({ producer });
    const message = producer.sent[0].messages[0];
    const body = JSON.parse(message.value);

    expect(body).toMatchObject({
      schemaVersion: 1,
      eventId: 'ev-0001',
      eventType: 'deal.created',
      aggregateType: 'deal',
      aggregateId: '100',
    });
    expect(body.payload.title).toBe('Acquire Initech');
    // Headers duplicate three body fields so a DLQ inspector or `kafka-console-consumer` can route
    // and filter without deserialising the payload.
    expect(message.headers['event-type']).toBe('deal.created');
    expect(message.headers['event-id']).toBe('ev-0001');
    expect(message.headers['schema-version']).toBe('1');
  });

  it('marks the batch failed and does not throw when the broker rejects it', async () => {
    const rows = [outboxRow({ id: 1 }), outboxRow({ id: 2 })];
    const { mod, queries } = await withDb(
      [undefined, rows, [], [], undefined],
      '#events/publisher.js'
    );
    const producer = fakeProducer({ failWith: new Error('Broker not available') });

    const result = await mod.publishOnce({ producer });

    // Resolved, not thrown: a broker outage is an expected state for a publisher, and throwing here
    // would kill the poll loop that is supposed to drain the backlog when Kafka returns.
    expect(result).toEqual({ claimed: 2, published: 0, failed: 2 });
    const sql = allSql(queries);
    expect(sql).not.toContain('"published_at" = now()');
    // Both rows get their own backoff, and the transaction COMMITS the failure markers — otherwise
    // the attempt counter would roll back with the failure and the row would retry immediately,
    // forever.
    expect(sql.match(/update "outbox"/g)).toHaveLength(2);
    expect(sql).toMatch(/commit/);
  });

  it('skips the cycle when another publisher holds the lock', async () => {
    const { mod, queries } = await withDb([], '#events/publisher.js');
    const producer = fakeProducer();

    const stopper = mod.startPublisher({
      producer,
      intervalMs: 60_000,
      // The lock is what keeps ordering intact during a rolling deploy, when two publisher pods
      // briefly overlap. Losing it is not an error — it means somebody else is doing the work.
      lock: async () => ({ acquired: false }),
    });
    await new Promise((r) => setTimeout(r, 10));
    stopper.stop();

    expect(mod.publisherStats.lockMissed).toBeGreaterThan(0);
    expect(queries).toHaveLength(0);
  });
});

describe('the consumer', () => {
  const kafkaMessage = (event, over = {}) => ({
    topic: 'acquisitions.events',
    partition: 0,
    message: {
      offset: '42',
      key: Buffer.from('deal:100'),
      value: Buffer.from(JSON.stringify(event)),
      headers: { 'event-type': Buffer.from(event?.eventType ?? 'unknown') },
      ...over,
    },
  });

  const event = (over = {}) => ({
    schemaVersion: 1,
    eventId: 'ev-0001',
    eventType: 'deal.created',
    aggregateType: 'deal',
    aggregateId: '100',
    occurredAt: '2026-09-05T10:00:00.000Z',
    payload: {
      id: 100,
      owner_id: 7,
      title: 'Acquire Initech',
      company: 'Initech',
      stage: 'sourced',
      amount_cents: 125000,
      currency: 'USD',
    },
    ...over,
  });

  it('claims the event and runs the handler in ONE transaction', async () => {
    const { mod, queries } = await withDb(
      [
        undefined, // begin
        [{ event_id: 'ev-0001' }], // insert into processed_events … returning
        [], // the handler's insert into notifications
        undefined, // commit
      ],
      '#events/consumer.js'
    );

    const result = await mod.handleMessage(kafkaMessage(event()), { producer: fakeProducer() });

    expect(result).toEqual({ handled: true });
    const sql = allSql(queries);
    // The claim and the effect commit together or not at all. Recording "I handled this" outside the
    // handler's transaction is the dual-write problem reappearing inside the fix for it.
    expect(queries[0].text.trim().toLowerCase()).toBe('begin');
    expect(sql).toContain('insert into "processed_events"');
    expect(sql).toContain('on conflict do nothing');
    expect(sql).toContain('insert into "notifications"');
    expect(queries.at(-1).text.trim().toLowerCase()).toBe('commit');
  });

  it('skips a redelivery without running the handler again', async () => {
    const { mod, queries } = await withDb(
      [
        undefined,
        [], // ON CONFLICT DO NOTHING matched an existing row, so nothing was returned
        undefined,
      ],
      '#events/consumer.js'
    );

    const result = await mod.handleMessage(kafkaMessage(event()), { producer: fakeProducer() });

    // At-least-once delivery must not mean at-least-once effect. This is the assertion that says so.
    expect(result).toEqual({ skipped: 'duplicate' });
    expect(allSql(queries)).not.toContain('insert into "notifications"');
  });

  it('records an event it has no handler for instead of failing forever', async () => {
    const { mod } = await withDb(
      [undefined, [{ event_id: 'ev-9' }], undefined],
      '#events/consumer.js'
    );

    const result = await mod.handleMessage(
      kafkaMessage(event({ eventId: 'ev-9', eventType: 'deal.archived' })),
      { producer: fakeProducer() }
    );

    // On a shared topic this is the normal case, not an error: a consumer group that does not care
    // about an event type must not spend the rest of its life failing on it.
    expect(result).toEqual({ skipped: 'no-handler' });
  });

  it('retries a failing handler, then dead-letters it so the partition can advance', async () => {
    const boom = new Error('handler exploded');
    // The transaction itself is fine; the HANDLER fails. Making every query throw would test the
    // database being down, which is a different (and retryable) condition.
    const { mod } = await withDb(({ text }) => {
      if (text.includes('"notifications"')) throw boom;
      if (text.includes('"processed_events"')) return [{ event_id: 'ev-poison' }];
      return [];
    }, '#events/consumer.js');
    const producer = fakeProducer();
    const message = kafkaMessage(event({ eventId: 'ev-poison' }));

    // Attempts 1 and 2 throw, which is what stops kafkajs committing the offset and causes the
    // redelivery.
    await expect(mod.handleMessage(message, { producer })).rejects.toThrow();
    await expect(mod.handleMessage(message, { producer })).rejects.toThrow();

    // The third RESOLVES, having parked the event. Throwing here instead is how one bad message
    // stops a pipeline: Kafka delivers a partition in order, so everything behind it waits forever.
    const result = await mod.handleMessage(message, { producer });
    expect(result).toMatchObject({ deadLettered: true, reason: 'handler-failed' });

    expect(producer.sent).toHaveLength(1);
    const dlq = producer.sent[0];
    expect(dlq.topic).toBe('acquisitions.events.dlq');
    // The payload is forwarded UNCHANGED, with the diagnosis in headers — a DLQ that rewrites the
    // body cannot be replayed into the main topic, which is the only thing a DLQ is for.
    expect(dlq.messages[0].value.toString()).toBe(message.message.value.toString());
    expect(dlq.messages[0].headers['dlq-reason']).toBe('handler-failed');
    expect(dlq.messages[0].headers['dlq-error']).toContain('handler exploded');
    expect(dlq.messages[0].headers['dlq-source-offset']).toBe('42');
  });

  it('dead-letters an unparseable message immediately', async () => {
    const { mod, queries } = await withDb([], '#events/consumer.js');
    const producer = fakeProducer();

    const result = await mod.handleMessage(
      { topic: 't', partition: 0, message: { offset: '7', value: Buffer.from('{not json') } },
      { producer }
    );

    // Retrying cannot make invalid JSON valid, so there is no point holding the partition for it —
    // and no transaction is opened at all.
    expect(result).toEqual({ deadLettered: true, reason: 'unparseable' });
    expect(queries).toHaveLength(0);
    expect(producer.sent[0].messages[0].headers['dlq-reason']).toBe('unparseable');
  });
});
