// ---------------------------------------------------------------------------
// The transactional outbox, and the table that makes the consumer idempotent.
//
// THE PROBLEM, STATED PRECISELY. A write and a publish are two systems:
//
//   await db.insert(deals)…      // Postgres
//   await producer.send(event)   // Kafka
//
// There is no ordering of those two lines that is correct. Publish first and a database
// failure leaves an event for a deal that does not exist. Write first and a broker failure
// (or a pod killed between the two) leaves a deal nobody was told about — silently, with a
// 201 already returned to the client. That is the dual-write problem, and no amount of
// try/catch fixes it, because the failure can happen between the two statements.
//
// THE OUTBOX. The event is written to a TABLE, in the SAME transaction as the domain change.
// One system, one atomic commit: either the deal and its event exist, or neither does. A
// separate publisher then reads the table and sends to Kafka, marking rows as published.
//
// WHAT THIS BUYS AND WHAT IT COSTS. It buys at-least-once delivery with no lost events and no
// phantom events, and it survives the broker being down for as long as the table can hold
// rows. It costs latency (the event is published after the commit, not during it) and it
// requires consumers to be idempotent, because a publisher that crashes after sending but
// before marking a row will send that row again. Exactly-once delivery is not on offer;
// exactly-once EFFECT is, and `processed_events` below is how.
// ---------------------------------------------------------------------------
import { sql } from 'drizzle-orm';
import {
  pgTable,
  bigserial,
  varchar,
  jsonb,
  timestamp,
  integer,
  text,
  index,
  primaryKey,
  check,
} from 'drizzle-orm/pg-core';

export const OUTBOX_MAX_ATTEMPTS = 8;

export const outbox = pgTable(
  'outbox',
  {
    id: bigserial('id', { mode: 'number' }).primaryKey(),

    // The partition key. Kafka guarantees order only WITHIN a partition, so every event for one
    // deal must carry the same key or a consumer can see "stage advanced" before "deal created".
    // `aggregate_type:aggregate_id` is that key — see src/events/publisher.js.
    aggregate_type: varchar('aggregate_type', { length: 64 }).notNull(),
    aggregate_id: varchar('aggregate_id', { length: 64 }).notNull(),

    event_type: varchar('event_type', { length: 128 }).notNull(),

    // A UUID generated by the WRITER, not the broker, and this is what makes the consumer able
    // to deduplicate: it is stable across every redelivery of the same event.
    event_id: varchar('event_id', { length: 64 }).notNull().unique(),

    // jsonb, not text: queryable, and it validates that what was stored is actually JSON at
    // write time rather than at read time in the consumer.
    payload: jsonb('payload').notNull(),

    created_at: timestamp('created_at', { withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    // NULL means "not yet published". The queue is a predicate rather than a status column, so
    // there is no state machine to get wrong and no way for a row to be both.
    published_at: timestamp('published_at', { withTimezone: true, precision: 3 }),

    attempts: integer('attempts').notNull().default(0),
    // When this row may next be attempted. A failed publish sets it into the future, which is how
    // backoff is expressed without a scheduler: the poller's WHERE clause simply cannot see the
    // row yet.
    available_at: timestamp('available_at', { withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    last_error: text('last_error'),
    // Set when a row has exhausted its attempts and has been sent to the dead-letter topic. It
    // stays in the table on purpose: a DLQ you cannot query from the database is a DLQ nobody
    // looks at.
    dead_lettered_at: timestamp('dead_lettered_at', { withTimezone: true, precision: 3 }),
  },
  (t) => [
    // THE POLLER'S INDEX, and its shape is the whole performance story of this table. The query
    // is "the oldest unpublished rows that are due now", so a PARTIAL index over exactly those
    // rows keeps the index the size of the BACKLOG rather than the size of history. Once a row is
    // published it leaves the index entirely, which is why a table with ten million published
    // events still has a poller that touches a handful of pages.
    index('outbox_unpublished_idx')
      .on(t.available_at, t.id)
      .where(sql`published_at is null`),
    // For the drill and for operators: "what is stuck?"
    index('outbox_dead_letter_idx')
      .on(t.dead_lettered_at)
      .where(sql`dead_lettered_at is not null`),
    check('outbox_attempts_nonnegative', sql`${t.attempts} >= 0`),
  ]
);

/**
 * Events this service has already handled.
 *
 * WHY A TABLE AND NOT A REDIS SET. The insert has to be in the SAME TRANSACTION as the handler's
 * own writes. With Redis it would be a second system again — the consumer could commit its work
 * and then fail to record that it did, and the redelivery would duplicate the effect. That is
 * the dual-write problem reappearing one layer down, which is a genuinely easy mistake to make
 * while implementing the fix for it.
 *
 * The primary key is (consumer_group, event_id): two different consumer groups must each be able
 * to process the same event, because they do different things with it.
 */
export const processedEvents = pgTable(
  'processed_events',
  {
    consumer_group: varchar('consumer_group', { length: 128 }).notNull(),
    event_id: varchar('event_id', { length: 64 }).notNull(),
    event_type: varchar('event_type', { length: 128 }).notNull(),
    processed_at: timestamp('processed_at', { withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (t) => [
    primaryKey({ columns: [t.consumer_group, t.event_id] }),
    // For the retention job that eventually trims this table. Without one it grows forever, and
    // "how do I clean up my dedupe table" is a question worth having an answer to before it is
    // 400 GB. A row is only useful for as long as a redelivery is possible.
    index('processed_events_processed_at_idx').on(t.processed_at),
  ]
);

export default outbox;
